### ISSUE TITLE
questions on setup live.glidernet.org

### ISSUE THREAD

**Issue by GliderGeek** [Meisterschueler/ogn-live-backend#1]
hey there,
thanks a lot for creating this and sharing it here. i am thinking about a personal project which is very much in line with what you have created and have some questions. i hope you dont mind me asking them here as i couldnt find an email adress.
cheers,
Matthijs

- does this repo represent the current state of the live.glidernet.org backend?

- how is this backend connected to the python gateway and thus the OGN stream?

**Comment by Meisterschueler** [comment]
Hi,
the repository for live.glidernet.org is [here](https://github.com/glidernet/ogn-live), most work is done by @cunimb and @snip with php.
I made this repository as a add-on for ogn-python, but now it is abandoned, because I already integrated it into ogn-python.

Main reasons for ogn-python are:
* ogn-live is written in PHP, I dont like it
* ogn logbook was not so performant -> I made the complete takeoff-landing recognition in SQL, this is much faster
* ktrax receiption diagrams are on another website and closed source
* ognrange is another thing and written in perl
With ogn-python there is only one database for all applications. And with flask it is absolutly no problem to serve the content which is needed for ogn-live/ognrange/logbook/...

**Comment by GliderGeek** [comment]
thanks for your reply.
regarding adding functionality to `ogn-python`, what do you think is the best approach? for instance i want to add another endpoint which takes in the plane IDs and returns only the current heights. should i make a fork of this repo and add my own endpoints? this was my initial plan, but i was a bit confused as this repo uses `ogn-python` as an installable package.

**Comment by Meisterschueler** [comment]
Just make a fork of `ogn-python` and add a new route in ogn_python/routes.py.
But: what do you want to get? Do you want to get just the current height for a plane? Or do you want to get an overview of all planes started from a given airport? I have the route for 'airport_detail.html' where you get details of the airport and all last movements of the devices who made a takeoff or a landing at this airport. Maybe you could enhance the route with the current altitude, then I would merge this into my repository.
